### ISSUE TITLE
Images not showing, asset not working

### ISSUE THREAD

**Issue by MostHated** [ChanUkLee/UnityExpandTool-Release#1]
Hey there,
    Not sure if the images are showing up on your end because they are coming from your own repo, but no one else can see them.

Maybe they are pointing to a private repo?

![](https://i.imgur.com/uKNwA1N.png)

![](https://i.imgur.com/UdX86Jv.png)

That said, I tried to import this to see what it was all about, since I could not actually see due to the image issue, but when I imported it, either as a package, or from source, it seemed that nothing worked, and I could not figure out exactly what was missing to make it work either. 

Just wanted to give you a heads up on all that.
Thanks,
-MH

**Comment by ChanUkLee** [comment]
Thank you, i fixed it :)
